<a href="https://colab.research.google.com/github/sr606/Python-Practice/blob/main/OCT24_numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
type(a)

list

In [4]:
b = [i*i for i in a]
print(b)

[1, 4, 9, 16, 25]


In [6]:
#x = np.array([1,2,3,4,5])
x = np.array(a)
type(x)

numpy.ndarray

numpy.ndarray

In [7]:
y = x ** 2
print(y)

[ 1  4  9 16 25]


In [8]:
# %timeit

l = range(2000000)
%timeit [i ** 2 for i in l]

694 ms ± 61.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
t = np.array(range(2000000))
%timeit t**2

2.82 ms ± 82.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
801 / 2.21

362.4434389140272

In [11]:
print(x)

[1 2 3 4 5]


In [12]:
x.ndim

1

In [13]:
x.shape

(5,)

In [14]:
x2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
x2.ndim

2

In [16]:
x2.shape

(4, 3)

In [17]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [18]:
x3 = np.array([[1,2,3,4,5],[4,5,6],[7,8,9],[10,11,12]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [19]:
t3 = np.array([[[1,2],[1,2],[2,3]],[[1,2],[1,2],[2,3]],[[1,2],[1,2],[2,3]]])
print(t3)

[[[1 2]
  [1 2]
  [2 3]]

 [[1 2]
  [1 2]
  [2 3]]

 [[1 2]
  [1 2]
  [2 3]]]


In [20]:
print(t3.ndim,t3.shape)

3 (3, 3, 2)


In [21]:
a = range(5)
for i in a:
  print(i)

0
1
2
3
4


In [27]:
#range(start,end,jump) / range(start,end, step-size)
b = range(5,100,5)
print(list(b))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [24]:
c = np.arange(5,100,5)
print(c)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [25]:
# numpy arange allow float data type for jump / step -size
c = np.arange(5,10,0.5)
print(c)

[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [29]:
s = np.array(["Hi","How","Are","You"])

In [30]:
print(s)

['Hi' 'How' 'Are' 'You']


In [31]:
l = [1,2,3,4,5.0,6]
a = np.array(l)
print(a)

[1. 2. 3. 4. 5. 6.]


In [33]:
l = [1,2,"Shraddha",4,5.0,6]
a = np.array(l)
print(a)

['1' '2' 'Shraddha' '4' '5.0' '6']


In [34]:
a = np.array([1,2,3,4,5.0,6], dtype = int)
print(a)

[1 2 3 4 5 6]


In [36]:
l = [1,2,3,"Shraddha",4,5.0,6]
a = np.array(l, dtype = int)
print(a)

ValueError: invalid literal for int() with base 10: 'Shraddha'

In [37]:
b = a.astype(float)
print(b)

[1. 2. 3. 4. 5. 6.]


In [42]:
l = [1,2,3,"Hello",4,5.0,6]
a = np.array(l)
print(a)
a.astype(int)

['1' '2' '3' 'Hello' '4' '5.0' '6']


ValueError: invalid literal for int() with base 10: 'Hello'

In [43]:
l = [-2,0,3,5,-1,0]
a = np.array(l,dtype=bool)
print(a)

[ True False  True  True  True False]


In [45]:
l = [-2, 0, 3, 5, -1, 0]
print(l[0])

-2


In [46]:
print(l[[4,3]])

TypeError: list indices must be integers or slices, not list

In [48]:
a = np.array(l)
print(a)

[-2  0  3  5 -1  0]


In [49]:
print(a)

[-2  0  3  5 -1  0]


In [50]:
print(l[[[4,3]]])

TypeError: list indices must be integers or slices, not list

In [52]:
print(a[[2,4]])

[ 3 -1]


In [53]:
# a[list of index]
# a[2,4] = > invalid
# a[[2,4]] => valid
print(a[3,5])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed