<a href="https://colab.research.google.com/github/sr606/Python-Practice/blob/main/Oct24_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
type(a)

list

In [3]:
b = [i*i for i in a]
print(b)

[1, 4, 9, 16, 25]


In [13]:
# x = np.array([1,2,3,4,5])
x = np.array(a)
type(x)

numpy.ndarray

In [6]:
y = x ** 2
print(y)

[ 1  4  9 16 25]


In [7]:
# %timeit

l = range(2000000)
%timeit [i**2 for i in l]

712 ms ± 64.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
t = np.array(range(2000000))
%timeit t**2

2.82 ms ± 65.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
801 / 2.21

362.4434389140272

In [15]:
print(x)

[1 2 3 4 5]


In [16]:
x.ndim

1

In [17]:
x.shape

(5,)

In [18]:
x2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
x2.ndim

2

In [20]:
x2.shape

(4, 3)

In [21]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim,a.shape)

1 (8,)


In [22]:
x3 = np.array([[1,2,3,4],[4,5,6],[7,8,9],[10,11,12]])
print(x3)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [24]:
t3 = np.array([[[1,2],[3,4],[5, 6]], [[1, 2], [3, 4], [5, 6]], [[1, 2], [2, 2], [3, 4]]])
print(t3)

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [2 2]
  [3 4]]]


In [25]:
t3.ndim

3

In [26]:
t3.shape

(3, 3, 2)

In [27]:
a = range(5)
for i in a:
  print(i)

0
1
2
3
4


In [28]:
# range(start, end, jump) / range(start, end, step - size)
b = range(5,100,5)
print(list(b))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [29]:
c = np.arange(5,100,5)
print(c)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [30]:
# nupmy arange allow float data type for jump / step-size
c = np.arange(5,10,0.5)
print(c)

[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [31]:
s = np.array(['Hi','How','are','you'])
print(s)

['Hi' 'How' 'are' 'you']


In [34]:
l = [1,2,3,4,5]
a = np.array(l)
print(a)

[1 2 3 4 5]


In [36]:
l = [1,2,4.0,3, 5]
a = np.array(l)
print(a)


[1. 2. 4. 3. 5.]


In [38]:
l = [1.2, 4, 5, 'hello']
a = np.array(l)
print(a)

['1.2' '4' '5' 'hello']


In [39]:
l = [1,2,3,4,5]
a = np.array(l, dtype = int)
print(a)

[1 2 3 4 5]


In [40]:
l = [1, 3.4, 5, 6,7, 'hello']
a = np.array(l, dtype = int)
print(a)

ValueError: invalid literal for int() with base 10: 'hello'

In [41]:
l = [1,2,3,4,5.6]
a = np.array(l,dtype = int)
print(a)

[1 2 3 4 5]


In [44]:
l = [-1,0,3,-4,5,0]
a = np.array(l,dtype = bool)
print(a)

[ True False  True  True  True False]


In [46]:
l = [-2,0,3,5,-1,0]
print(l[2])

3


In [47]:
a = np.array(l)
print(a)

[-2  0  3  5 -1  0]


In [48]:
print(l[[2,4]])

TypeError: list indices must be integers or slices, not list

In [49]:
print(a)

[-2  0  3  5 -1  0]


In [50]:
print(a[[2,4]])

[ 3 -1]


In [51]:
# a[list of index ]
# a[2,4] => invalid
# a[[2,4]] => valid

print(a[2,4])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [52]:
lst = [1,4,2,1]
print(a[lst])

[ 0 -1  3  0]


In [53]:
lst = [0, -1]
print(a[lst])

[-2  0]


In [54]:
lst = [0,100]
print(a[lst])

IndexError: index 100 is out of bounds for axis 0 with size 6

In [55]:
m1  = np.array([1,2,3,4,5,6,7,8,9,10])
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
print(m1[0:5])

[1 2 3 4 5]


In [57]:
# a[start : end : jump]
print(m1[3 : 6 : 2])

[4 6]


In [60]:
print(m1[::-1])
print(m1[6:0:-2])

[10  9  8  7  6  5  4  3  2  1]
[7 5 3]


In [61]:
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [63]:
m1 < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [64]:
m1 % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [65]:
a = np.array([-1,3,100,-5,-20,53,28])
lst =[True,True,False,False,True,True,False]
print(a[lst])

[ -1   3 -20  53]


In [66]:
print(a)

[ -1   3 100  -5 -20  53  28]


In [67]:
a < 0

array([ True, False, False,  True,  True, False, False])

In [68]:
a[a<0]

array([ -1,  -5, -20])

In [69]:
a[a>10]

array([100,  53,  28])

In [71]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])
a[2:] = b[::-1]
print(a)

[1 2 6 7 8]


In [72]:
# https://drive.google.com/file/d/1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK/view
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 8.07MB/s]


In [73]:
score = np.loadtxt('survey.txt',dtype = 'int')

In [74]:
cnt = len(score)

In [75]:
p = len(score)

In [76]:
p = score[score >= 9]
len(p)

609

In [77]:
d = score[score < 7]
len(d)

332

In [78]:
promoters = len(p) /cnt * 100
detractors = len(d) /cnt * 100
nps = promoters - detractors
print(nps)

23.73607540702657


In [79]:
print(round(nps,2))

23.74
