<a href="https://colab.research.google.com/github/sr606/Python-Practice/blob/main/Oct_24_Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array(range(16))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [2]:
a.shape

(16,)

In [3]:
a.ndim

1

In [4]:
a.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [5]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
a.reshape(5,3)

ValueError: cannot reshape array of size 16 into shape (5,3)

In [7]:
a.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [9]:
a.reshape(6,-1)

ValueError: cannot reshape array of size 16 into shape (6,newaxis)

In [10]:
a.reshape(-1,3)

ValueError: cannot reshape array of size 16 into shape (3)

In [11]:
b = a.reshape(-1,2)

In [13]:
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [14]:
len(b)

8

In [15]:
len(b[0])

2

In [16]:
len(b[1])

2

In [17]:
b.shape

(8, 2)

In [18]:
np.array(b).size

16

In [20]:
a = np.array(range(100))
a.reshape(25,4) #10, #10

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [21]:
a.reshape(10,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [22]:
a.reshaep(-1,-1)

AttributeError: 'numpy.ndarray' object has no attribute 'reshaep'

In [23]:
a.size

100

In [24]:
b.size

16

In [25]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [27]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a[1][2]

6

In [29]:
a[1,2] #a[i][j] = a[i,j]

6

In [31]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b[[3,5,1]]

array([3, 5, 1])

In [35]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
#(0,1),(1,2),(2,0)
#advance indexing
a[[0,1,2],[1,2,0]]

array([1, 6, 8])

In [38]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
#x[index]  -> 1 element
#x[ list of indexes ] -> mutable elements
lst = [4,0,1]
x[lst]

array([4, 0, 1])

In [40]:
y = np.arange(12).reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
# y[i,j] -> 1 element
# y[list of rows, list of columns ] -> multiple elements
rows = [2,0,1]
cols = [0,1,-1]
# (2,0), (0,1), (1,1)
y[rows,cols]

array([8, 1, 7])

In [42]:
rows = [2,0,3,4 ]
cols = [1,3,-1]
y[rows,cols]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (4,) (3,) 

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [46]:
x[2:5]

array([2, 3, 4])

In [47]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
y[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [49]:
y[1:2]

array([[4, 5, 6, 7]])

In [50]:
y[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
y[:,:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [52]:
y[0:1,1:3]

array([[1, 2]])

In [53]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])