<a href="https://colab.research.google.com/github/sr606/Python-Practice/blob/main/ProblemSolving_on_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Sample DataFrame
data = {
    'name': ['John', 'Alice', 'Bob', 'Eve', 'Mike', 'Sophia', 'Chris', 'Laura'],
    'profession': ['Engineer', 'Doctor', 'Lawyer', 'Artist', 'Engineer', 'Doctor', 'Lawyer', 'Artist'],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'age': [28, 35, 24, 29, 23, 30, 26, 31],
    'review': ['Excellent', 'Good', 'Average', 'Excellent', 'Good', 'Average', 'Poor', 'Excellent'],
    'rating': [4.5, 4.0, 3.0, 4.5, 4.0, 3.5, 2.0, 4.5]
}

df = pd.DataFrame(data)
print(df)


     name profession  gender  age     review  rating
0    John   Engineer    Male   28  Excellent     4.5
1   Alice     Doctor  Female   35       Good     4.0
2     Bob     Lawyer    Male   24    Average     3.0
3     Eve     Artist  Female   29  Excellent     4.5
4    Mike   Engineer    Male   23       Good     4.0
5  Sophia     Doctor  Female   30    Average     3.5
6   Chris     Lawyer    Male   26       Poor     2.0
7   Laura     Artist  Female   31  Excellent     4.5


In [ ]:
def specific_customers(df):
    ''' df is a dataframe with columns ['name', 'profession', 'gender', 'age', 'review', 'rating']
        Output -> A series with required names is expected to be returned'''
    # YOUR CODE GOES HERE

    # Select male professionals
    df_new = df[df['gender']== 'Male']
    return df_new

In [ ]:
df_new = df[df['gender']== 'Male']
df_new

name profession gender  age     review  rating
0   John   Engineer   Male   28  Excellent     4.5
2    Bob     Lawyer   Male   24    Average     3.0
4   Mike   Engineer   Male   23       Good     4.0
6  Chris     Lawyer   Male   26       Poor     2.0

In [ ]:
df_new = df[df['gender']== 'Male']
df_new = df_new[(df_new['age'] >= 23) & (df_new['age'] <= 30)]
df_new['name']

0     John
2      Bob
4     Mike
6    Chris
Name: name, dtype: object

In [ ]:
import pandas as pd
def specific_customers(df):
    ''' df is a dataframe with columns ['name', 'profession', 'gender', 'age', 'review', 'rating']
        Output -> A series with required names is expected to be returned'''
    # YOUR CODE GOES HERE

    # Select male professionals
    #df_new = df['gender'] == 'male'

    # Filter for age group 23-3
    df_new = df.loc[(df['profession'] == 'Engineer') & (df['profession'] == 'Artist') & (df['rating'] > 3.0) & (df['rating'] <= 4.5)]
    return df_new['name']

In [ ]:
specific_customers(df)

Series([], Name: name, dtype: object)

In [ ]:
df_new = df.loc[((df['profession'] == 'Engineer') | (df['profession'] == 'Artist')) & (df['rating'] > 3.0) & (df['rating'] <= 4.5)]
df_new['name']

0     John
3      Eve
4     Mike
7    Laura
Name: name, dtype: object

### Question-1

Question:
Create a function that generates two 1D NumPy arrays:
- Array A: 1D array with 10 evenly spaced values between 0 and 1.
- Array B: 1D array with values from 1 to 10.

Perform the following operations:

- Multiply A and B element-wise.
- Round the result to 2 decimal places.
- Create a new array C that contains only the elements from the result where - the rounded value is greater than 2.5.
- Convert C to integer data type.
- Return arrays A, B, and C, along with the data types of A and C.

In [ ]:
import numpy as np
def array_operations():
  A = np.linspace(0,1,10)
  B = np.arange(1,11)
#Multiply A and B element-wise.

  product = A*B

#Round the result to 2 decimal places.
  C = np.round(product,2)

# Create a new array C that contains only the elements from the result where - the rounded value is greater than 2.5.
  C = C[C > 2.5]
# 5. Convert C to integer data type.
  C = C.astype(int)

  # 6. Return arrays A, B, and C, along with the data types of A and C.

  return A,B,C,A.dtype, C.dtype

A, B, C, A_data_type, C_data_type = array_operations()

print(f'A: {A}')
print(f'B: {B}')
print(f'C: {C}')
print(f'A Data Type: {A_data_type}')
print(f'C Data Type: {C_data_type}')


A: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
B: [ 1  2  3  4  5  6  7  8  9 10]
C: [ 3  4  6  8 10]
A Data Type: float64
C Data Type: int64


### Question-2
Create a function that performs the following tasks:

1. Generate a 1D array 'A' with 20 evenly spaced values between -5 and 5.
2. Create a 2D array 'B' by reshaping A into a 4x5 matrix.
3. Round all elements in B to 1 decimal place.
4. Create a mask for all positive elements in B.
5. Replace all masked elements with their respective indices (use multi-dimensional indexing).
6. Slice the resulting array to keep only the middle two rows.
7. Convert the sliced array to float32 data type.

Return the original 1D array A, the final sliced and modified 2D array, the shape of the final array, and the number of dimensions of the final array.|


In [ ]:
A = np.linspace(-5,5,20)
B = A.reshape(4,5)

In [ ]:
A

array([-5.        , -4.47368421, -3.94736842, -3.42105263, -2.89473684,
       -2.36842105, -1.84210526, -1.31578947, -0.78947368, -0.26315789,
        0.26315789,  0.78947368,  1.31578947,  1.84210526,  2.36842105,
        2.89473684,  3.42105263,  3.94736842,  4.47368421,  5.        ])

In [ ]:
B

array([[-5.        , -4.47368421, -3.94736842, -3.42105263, -2.89473684],
       [-2.36842105, -1.84210526, -1.31578947, -0.78947368, -0.26315789],
       [ 0.26315789,  0.78947368,  1.31578947,  1.84210526,  2.36842105],
       [ 2.89473684,  3.42105263,  3.94736842,  4.47368421,  5.        ]])

In [ ]:
B = np.round(B,1)

B

array([[-5. , -4.5, -3.9, -3.4, -2.9],
       [-2.4, -1.8, -1.3, -0.8, -0.3],
       [ 0.3,  0.8,  1.3,  1.8,  2.4],
       [ 2.9,  3.4,  3.9,  4.5,  5. ]])

In [ ]:
flatten_array = B.flatten()
flatten_array

array([-5. , -4.5, -3.9, -3.4, -2.9, -2.4, -1.8, -1.3, -0.8, -0.3,  0.3,
        0.8,  1.3,  1.8,  2.4,  2.9,  3.4,  3.9,  4.5,  5. ])

In [ ]:
index_array = np.arange(0, len(flatten_array))
index_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
mask = flatten_array > 0
mask

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
index_array = np.arange(0, len(flatten_array))[mask]
index_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
index_array_2D = index_array.reshape(B.shape)
index_array_2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
mask_2D = mask.reshape(B.shape)
B[mask_2D] = index_array_2D[mask_2D]
B

array([[-5. , -4.5, -3.9, -3.4, -2.9],
       [-2.4, -1.8, -1.3, -0.8, -0.3],
       [10. , 11. , 12. , 13. , 14. ],
       [15. , 16. , 17. , 18. , 19. ]])

In [ ]:
def array_manipulation_2():
  #Generate a 1D array 'A' with 20 evenly spaced values between -5 and 5.
  A = np.linspace(-5,5,20)
  #Create a 2D array 'B' by reshaping A into a 4x5 matrix.
  B = A.reshape(4,5)
  #Round all elements in B to 1 decimal place.
  B = np.round(B,1)
  #Create a mask for all positive elements in B.
  mask = B > 0
  #Replace all masked elements with their respective indices (use multi-dimensional indexing).
  B[mask] = np.arange(0, len(B.flatten())).reshape(B.shape)[mask]
  #Slice the resulting array to keep only the middle two rows.
  B_sliced = B[1:3, :]
  #Convert the sliced array to float32 data type.
  B_float = B_sliced.astype(float)

  return A,B_float, B_float.shape, B_float.ndim

A, B_float, B_float_shape, B_float_dimensions = array_manipulation_2()


print(f'A: {A}')
print(f'B_float: {B_float}')
print(f'B float shape : {B_float_shape}')
print(f'B float dimensions : {B_float_dimensions}')

A: [-5.         -4.47368421 -3.94736842 -3.42105263 -2.89473684 -2.36842105
 -1.84210526 -1.31578947 -0.78947368 -0.26315789  0.26315789  0.78947368
  1.31578947  1.84210526  2.36842105  2.89473684  3.42105263  3.94736842
  4.47368421  5.        ]
B_float: [[-2.4 -1.8 -1.3 -0.8 -0.3]
 [10.  11.  12.  13.  14. ]]
B float shape : (2, 5)
B float dimensions : 2


### Question-3


Question:
Create a function that performs the following operations:

1. Generate a 1D array 'A' with values from 0 to 24.
2. Create a 2D array 'B' to convert A into a 5x5 matrix (use nested lists).
3. Create a mask for elements in B that are multiples of 3.
4. Use the mask to replace these elements with -1.
5. Slice the array to keep only the 2nd and 4th columns.
6. Round all elements in the resulting array to the nearest integer.
7. Convert the array to float32 data type.

Return the original 1D array A, the final modified 2D array, the shape of the final array, and the number of dimensions of the final array.

In [6]:
import numpy as np
def array_operations():
  #enerate a 1D array 'A' with values from 0 to 24.
  A = np.arange(0,25)

  # 2. Create a 2D array 'B' to convert A into a 5x5 matrix (use nested lists).
  B = np.array([A[i: i+5].tolist() for i in range(0,25,5)])

  # 3. Create a mask for elements in B that are multiples of 3.
  mask = (B % 3 == 0)

  # 4. Use the mask to replace these elements with -1.
  B[mask]  = -1

  # 5. Slice the array to keep only the 2nd and 4th columns
  B_sliced = B[:, 1:3]

  # 6. Round all elements in the resulting array to the nearest integer.

  B_round = np.round(B_sliced)
  B_round = B_round.astype(float)


  return A, B_round, B_round.shape, B_round.ndim


A,B_float, B_float.shape, B_float_dimensions = array_operations()
print(f' A: {A}\n')
print(f' B: {B_float}\n')
print(f'B shape {B_float.shape}\n')
print(f'B Dimensions: {B_float_dimensions}')



 A: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

 B: [[ 1.  2.]
 [-1.  7.]
 [11. -1.]
 [16. 17.]
 [-1. 22.]]

B shape (5, 2)

B Dimensions: 2
